### ISSUE TITLE
goToLobby bug

### ISSUE THREAD

**Issue by ldworkin** [ldworkin/meteor-prisoners-dilemma#1]
```
I20150720-17:42:32.872(0)? Exception while invoking method 'goToLobby' TypeError: Cannot call method 'sendUserToLobby' of undefined
I20150720-17:42:32.873(0)?     at [object Object].Meteor.methods.goToLobby (app/server/server.js:46:7)
I20150720-17:42:32.873(0)?     at maybeAuditArgumentChecks (packages/ddp/livedata_server.js:1617:1)
I20150720-17:42:32.873(0)?     at packages/ddp/livedata_server.js:648:1
I20150720-17:42:32.873(0)?     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
I20150720-17:42:32.874(0)?     at packages/ddp/livedata_server.js:647:1
I20150720-17:42:32.875(0)?     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
I20150720-17:42:32.875(0)?     at [object Object]._.extend.protocol_handlers.method (packages/ddp/livedata_server.js:646:1)
I20150720-17:42:32.875(0)?     at packages/ddp/livedata_server.js:546:1
```

**Comment by mizzao** [comment]
You fixed this in d38080762759bf8d9aa7bd6341ef5c3566245f0c :)
